global:
  api:
    secretName: "api-key"

# -- API Server configuration
server:
  enabled: true
  image:
    repository: <server_repository>
    tag: "latest"
  imagePullPolicy: Always

  ingress:
    enabled: true
    className: native-ic
    annotations:
      nginx.ingress.kubernetes.io/upstream-vhost: "<lb_reserved_ip>"
      oci-native-ingress.oraclecloud.com/http-listener-port: "8000"
      oci-native-ingress.oraclecloud.com/protocol: TCP

  service:
    http:
      type: "NodePort"

  # -- Oracle Cloud Infrastructure Configuration
  oci:
    tenancy: "ocid1.tenancy.oc1..aaaaaaaaj4ccqe763dizkrcdbs5x7ufvmmojd24mb6utvkymyo4xwxyv3gfa"
    region: "eu-frankfurt-1"

  # -- Oracle Autonomous Database Configuration
  adb:
    enabled: true
    ocid: "ocid1.autonomousdatabase.oc1.eu-frankfurt-1.antheljtknuwtjiapq6luydxfuzlcxt2e2w3l2toh32ww3qdti4qdf72lsiq"
    mtls:
      enabled: true
    authN:
      secretName: "db-authn"
      usernameKey: "username"
      passwordKey: "password"
      serviceKey: "service"

  models:
    ollama:
      enabled: false

client:
  enabled: true
  image:
    repository: <client_repository>
    tag: "latest"
  imagePullPolicy: Always

  ingress:
    enabled: true
    className: native-ic
    annotations:
      nginx.ingress.kubernetes.io/upstream-vhost: "<lb_reserved_ip>"
      oci-native-ingress.oraclecloud.com/http-listener-port: "80"
      oci-native-ingress.oraclecloud.com/protocol: TCP

  service:
    http:
      type: "NodePort"

  features:
    disableTestbed: "false"
    disableApi: "false"
    disableTools: "false"
    disableDbCfg: "false"
    disableModelCfg: "false"
    disableOciCfg: "false"
    disableSettings: "false"

ollama:
  enabled: true
  models:
    - llama3.1
    - mxbai-embed-large
  resources:
    limits:
      nvidia.com/gpu: 1