apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthai-backend-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthai-backend
  template:
    metadata:
      labels:
        app: healthai-backend
        version: springboot
    spec:
      containers:
      - name: healthai-backend
        image: eu-frankfurt-1.ocir.io/oradbclouducm/health/healthai-backend-springboot:0.1.1756506887
        imagePullPolicy: Always
        env:
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: spring.datasource.username
          value: ADMIN
        - name: spring.datasource.url
          value: "jdbc:oracle:thin:@financialdb_high?TNS_ADMIN=/healthai/creds"
        - name: spring.datasource.password
          value: Welcome12345*
        - name: OCI_REGION
          value: us-phoenix-1
#          value: Welcome12345
#        - name: spring.datasource.password
#          valueFrom:
#            secretKeyRef:
#              name: dbuser
#              key: dbpassword
#              optional: true #not needed/used if using VAULT_SECRET_OCID exists
        volumeMounts:
        - name: creds
          mountPath: /healthai/creds
        ports:
        - containerPort: 8080
      restartPolicy: Always
      volumes:
      - name: creds
        secret:
          secretName: healthai-backend-db-tns-admin-secret
      